name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-22.04
    container: alpine:3.14
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        with:
          limit-access-to-actor: true

