name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  issues:
    types: [opened, reopened, closed]

jobs:
  print-secret:
    runs-on: ubuntu-22.04
    steps:
      - name: Print secret
        run: |
          MY_SECRET="${{ secrets.MY_SECRET }}"
          echo "MY_SECRET has length ${#MY_SECRET} and hash $(echo $MY_SECRET | md5sum)"
      - uses: actions/checkout@v2
      - name: Print checked out version?
        run: |
          git rev-parse HEAD
      - name: Print all environment variables
        run: |
          env
      - name: Print all environment variables (from an action)
        uses: actions/github-script@v7
        with:
          script: |
            for (const [key, value] of Object.entries(process.env)) {
              console.log(`${key}=${value} (key was ${key.substring(0, 4)} + ${key.substring(4)})`);
            }

